# Generated by Django 3.0.8 on 2020-07-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food_code', models.IntegerField()),
                ('Main_food_description', models.TextField()),
                ('WWEIA_Category_description', models.TextField()),
                ('Energy', models.FloatField()),
                ('Protein', models.FloatField()),
                ('Carbohydrate', models.FloatField()),
                ('Sugar', models.FloatField()),
                ('Fiber', models.FloatField()),
                ('Alcohol', models.FloatField()),
                ('Vitamin_C', models.FloatField()),
                ('Vitamin_A', models.FloatField()),
                ('Vitamin_B12', models.FloatField()),
                ('Vitamin_D', models.FloatField()),
                ('Calcium', models.FloatField()),
                ('Phosphorus', models.FloatField()),
                ('Magnesium', models.FloatField()),
                ('Iron', models.FloatField()),
                ('Zinc', models.FloatField()),
                ('Selenium', models.FloatField()),
                ('Potassium', models.FloatField()),
                ('Sodium', models.FloatField()),
                ('Copper', models.FloatField()),
                ('Theobromine', models.FloatField()),
                ('Caffeine', models.FloatField()),
                ('Portion_description', models.TextField()),
                ('Portion_weight', models.FloatField()),
            ],
        ),
    ]
